# -*- coding: utf-8 -*-
"""Python_analysis_tns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJ9YPbGhrbTAgfScEXBWli1tTYf7CTrx
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install pingouin

import pandas as pd
from scipy.stats import f_oneway
import seaborn as sns
import pingouin as pg

# importing data and naming columns respectively

data = pd.read_csv("/content/drive/My Drive/All_Raw_Data_Active_and_Sham_CSV.csv")

data.columns = ['Group', 'Subject', 'Block', 'Trial', 'Condition', 'ReactionTime']

data['Group'] = data['Group'].astype('category')
data['Block'] = data['Block'].astype('category')
data['Condition'] = data['Condition'].astype('category')
data['UniqueSubjectID'] = data['Group'].astype(str) + '_' + data['Subject'].astype(str)

aov = pg.mixed_anova(dv='ReactionTime', between='Group', within='Block', subject='UniqueSubjectID', data=data)
print(aov)

data['Combined'] = data['Condition'].astype(str) + "_" + data['Block'].astype(str)
aov = pg.mixed_anova(dv='ReactionTime', between='Group', within='Combined', subject='UniqueSubjectID', data=data)
print(aov)

!pip install statsmodels

# Tried to use anova_lm by statsmodels as mentioned in https://www.statology.org/three-way-anova-python/

import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

model = ols('ReactionTime ~ C(Group) * C(Condition) * C(Block)', data=data).fit()
aov_table = anova_lm(model, typ=2)
print(aov_table)

# Tried to use anova_lm with removing outliers and fill with NA

def remove_outliers_and_fill(df, column='ReactionTime'):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    condition = ~((df[column] >= (Q1 - 1.5 * IQR)) & (df[column] <= (Q3 + 1.5 * IQR)))
    df.loc[condition, column] = pd.NA
    return df

data_clean = remove_outliers_and_fill(data)

model = ols('ReactionTime ~ C(Group) * C(Condition) * C(Block)', data=data_clean).fit()
aov_table = anova_lm(model, typ=2)

print(aov_table)